name: Build Tweak
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # YAHAN HAI ASALI FIX: ldid install karna
      - name: Install ldid (The Missing Tool)
        run: brew install ldid

      - name: Checkout Theos Natively
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          submodules: recursive
          path: theos

      - name: Install iOS SDK
        run: |
          curl -L https://github.com/theos/sdks/archive/master.zip -o sdks.zip
          unzip -q sdks.zip
          mv sdks-master/* theos/sdks/
          rm -rf sdks-master sdks.zip

      - name: Compile and Package
        run: |
          export THEOS=${{ github.workspace }}/theos
          make package FINALPACKAGE=1

      - name: Upload Tweak File
        uses: actions/upload-artifact@v4
        with:
          name: StarMaker-Final-Bypass
          path: packages/*.deb
